baseline: .swiftlint.baseline.json

disabled_rules:
  - line_length
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - force_unwrapping
  - empty_string

analyzer_rules:
  - explicit_self

excluded:
  - Pods
  - qbremoteTests
  - qbremoteUITests

identifier_name:
  min_length:
    warning: 1
    error: 1
  allowed_symbols:
    - _

function_body_length:
  warning: 150
  error: 200
